# This adds the various environment variables needed by the GCP PubSub Source controller. It also
# adds anything needed by those environment variables (e.g. the secret volume whose location is in
# a env variable).

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: ENABLE_GCPPUBSUB_SOURCE
              value: 'true'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: GCPPUBSUB_RA_IMAGE
              value: github.com/knative/eventing-sources/cmd/gcppubsub_receive_adapter
            - name: GCPPUBSUB_RA_SERVICE_ACCOUNT
              value: default
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gcppubsub-source-key
