# Copyright 2019 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventing-sources-controller
rules:
# Sources admin
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - githubsources
  verbs: &everything
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

  # ContainerSource from eventing
- apiGroups:
    - sources.eventing.knative.dev
  resources:
    - containersources
    - containersources/status
    - containersources/finalizers
  verbs: *everything

# Sources finalizer
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - githubsources/finalizers
  verbs: *everything

# Source statuses update
- apiGroups:
  - sources.eventing.knative.dev
  resources:
  - githubsources/status
  verbs:
  - get
  - update
  - patch

# Deployments admin
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: *everything

# Knative Services admin
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs: *everything

# Secrets read
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch

# Events admin
- apiGroups:
  - ""
  resources:
  - events
  verbs: *everything

# EventTypes admin
- apiGroups:
  - eventing.knative.dev
  resources:
  - eventtypes
  verbs: *everything
