# Adds namespace to all resources.
namespace: knative-sources

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").

resources:
  - sources_v1alpha1_awssqssource.yaml
  - istio_egress.yaml
  - manager.yaml
  - rbac_role.yaml
  - rbac_role_binding.yaml

patches:
  - conditions_patch.yaml
